### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by fronto** [larsks/undocker#16]
Apparently unable to read a docker layer or part of it. Looks like a permissions issue.

```bash
$docker save jenkins/jenkins:lts-alpine | undocker -i -o unpacked jenkins/jenkins:lts-alpine
Traceback (most recent call last):
  File "/usr/local/bin/undocker", line 9, in <module>
    load_entry_point('undocker==5', 'console_scripts', 'undocker')()
  File "build/bdist.linux-x86_64/egg/undocker.py", line 131, in main
  File "build/bdist.linux-x86_64/egg/undocker.py", line 61, in find_layers
AttributeError: 'ExFileObject' object has no attribute 'readable'
```
Is this a problem with the image or the undocker project??

**Comment by larsks** [comment]
Thanks for the report! I've just pushed a change that should correct the issue. It looks like this stems from some weirdness in Python 2 (see https://stackoverflow.com/q/34447623/147356 for details). I've used an ugly hack to work around the problem; it seems sufficient for undocker to run successfully.

**Comment by fronto** [comment]
Thanks for the quick update!
