### ISSUE TITLE
OSError: [Errno 21] Is a directory: 'var/lib/apt/lists/partial'

### ISSUE THREAD

**Issue by parmentelat** [larsks/undocker#17]
Hey there

Thanks for coming up with this tool; I'm giving it a try and am running into the following issue:

```
root@fit06:~/image# docker save fitr2lab/ubuntu16 | python3 ../undocker/undocker.py
Traceback (most recent call last):
  File "../undocker/undocker.py", line 174, in <module>
    main()
  File "../undocker/undocker.py", line 167, in main
    os.unlink(newpath)
IsADirectoryError: [Errno 21] Is a directory: 'var/lib/apt/lists/partial'
```

I expect the issue to be easily reproducible from that same image which is published at dockerhub  
The directory that I am trying to populate is empty  
I am using the latest version of undocker.py as available at github  (which btw does not seem to be the exact same one as what I first got with pip, but another matter..)

The host OS is this:
```
root@fit06:~/image# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

root@fit06:~/image# python3 --version
Python 3.5.2
```

**Comment by parmentelat** [comment]
It seems like the outcome depends on the way it is called; 

# works fine

if I ask undocker to create a new dir for me it's fine

```
root@fit06:~# docker save fitr2lab/ubuntu16 | python3 ~/undocker/undocker.py -o image-ok
```

# won't work

If now I create it myself, go there to extract, the issue shows up

```
root@fit06:~# mkdir image-ko; cd image-ko; docker save fitr2lab/ubuntu16 | python3 ~/undocker/undocker.py
Traceback (most recent call last):
  File "/root/undocker/undocker.py", line 174, in <module>
    main()
  File "/root/undocker/undocker.py", line 167, in main
    os.unlink(newpath)
IsADirectoryError: [Errno 21] Is a directory: 'var/lib/apt/lists/partial'
```

and unsurprisingly it's the same if I explicitly specify `-o .` 

***
is this the intended behaviour, in which case I misunderstood something ?

In any case I find it misleading that the default for the -o option is '.'

**Comment by larsks** [comment]
> In any case I find it misleading that the default for the -o option is '.'

In what way is it "misleading"? I'm not trying to trick you.

**Comment by parmentelat** [comment]
I did not mean to suggest anything of that kind.

all I'm saying is that because the default for -o is `.`, it feels only natural to start and use the tool this way; except that it's exactly the one use case that triggers the problem.

**Comment by larsks** [comment]
That's not "misleading", that's a bug. When using `-o <somedirectory>`, it turns out that undocker isn't handling whiteouts correctly.
