### ISSUE TITLE
Make undocker work on a saved image

### ISSUE THREAD

**Issue by mortenlj** [larsks/undocker#19]
Since the first thing undocker does is to take the stdin and write to a temp file, would it be possible to allow the user to save to disk first, and then just run undocker on the already saved image? 

For instance, something like this:

```
docker save busybox -o /tmp/busybox.tar
undocker -i -o /tmp/filesystem busybox /tmp/busybox.tar
```

**Comment by aidecoe** [comment]
Absolutely, try: `undocker -i -o /tmp/filesystem busybox </tmp/busybox.tar`

**Comment by mortenlj** [comment]
I don't remember why I wanted this feature, and as mentioned by @aidecoe , there is a workaround.

Only problem is that the workaround just means you need twice the amount of space on your disk, as it will stream the file into undocker, which will write that stream to a new temporary file, and work on that file.

It would be more efficient to just use the supplied file directly, instead of creating a copy.

However, I don't need this feature anymore, I dropped using undocker entirely, so I'm closing the issue. If anyone disagrees, please reopen.
