### ISSUE TITLE
Turn image layers into standalone images

### ISSUE THREAD

**Issue by mvorisek** [larsks/undocker#25]
This is a question. Docker prevents to use the source layers as an image, the ID is missing (`<missing>` is shown).

My question is, can I use this too to extract all image layers into standalone images with image ID available for each layer?

**Comment by larsks** [comment]
It's certainly not designed to do that, but with some external automation you could extract layers into individual directories and then `docker build` those into images, I guess, except you would lose non-file metadata (things like enviornment variables, command/entrypoint, etc).
