### ISSUE TITLE
OSError: [Errno 2] No such file or directory: 'etc/rcS.d/.wh.S02mountdevsubfs.sh'

### ISSUE THREAD

**Issue by ericfont** [larsks/undocker#8]
I'm trying to extract the contents of my build: https://hub.docker.com/r/ericfont/armv7hf-debian-qemu-appimagekit/builds/bnywuskzyttfjagcp6o6at5/
<pre>docker save ericfont/armv7hf-debian-qemu-appimagekit:helloworld | /usr/bin/python2 ~/undocker.py -o armv7hf-debian-qemu-appimagekit-helloworld ericfont/armv7hf-debian-qemu-appimagekit:helloworld</pre>
produces this error:
<pre>Traceback (most recent call last):
  File "/home/e/undocker.py", line 145, in <module>
    main()
  File "/home/e/undocker.py", line 140, in main
    os.unlink(path)
OSError: [Errno 2] No such file or directory: 'etc/rcS.d/.wh.S02mountdevsubfs.sh'</pre>

I don't know what that means.  I'm on Parabola linux x86-64 and armv7a.  I'm also noticing that the output folder doesn't seem to contain everything, becuase I ran apt-get install inside the build, but I don't see those resulting files in the output folder.

**Comment by cweiske** [comment]
I have the same problem. A file shall get removed that does not exist, and undocker breaks on this:

```
INFO:undocker:removing path var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty_Release
Traceback (most recent call last):
  File "/usr/local/bin/undocker", line 9, in <module>
    load_entry_point('undocker==5', 'console_scripts', 'undocker')()
  File "/usr/local/lib/python2.7/dist-packages/undocker.py", line 140, in main
    os.unlink(path)
OSError: [Errno 2] No such file or directory: 'var/lib/apt/lists/.wh.archive.ubuntu.com_ubuntu_dists_trusty_Release'
```
