### ISSUE TITLE
failed to find image ubuntu with tag latest

### ISSUE THREAD

**Issue by ehsanmostajeran** [larsks/undocker#9]
Hi,
I am trying to get layers of an image. Image name is ubuntu:14.04.
But I face this error.

`docker save ubuntu:14.04 | undocker --layers
ERROR:undocker:failed to find image ubuntu with tag latest`

I appreciate if you could guide to solve it.

**Comment by kppullin** [comment]
After looking at the script it assumes you want `latest` if the "image" is not specified as the last argument to the `undocker` command.

So here's what you'll want to run instead:

`docker save ubuntu:14.04 | undocker --layers ubuntu:14.04`
